### ISSUE TITLE
[feat] Restore terminal buffer state

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#12]
Well, I'm not sure whether this is possible. Say I have a terminal buffer in my current project, then I run commands like `ls -al` in it. Then I close the project and restore it. What I expect to see after restoring is that I can use `<C-p>` to get the last command, i.e. `ls -al`, I entered. Any idea how to achieve this?

**Comment by GnikDroy** [comment]
> What I expect to see after restoring is that I can use <C-p> to get the last command, i.e. ls -al, I entered.

The last command or the output of the last command? For the command itself, this history is saved by the shell. So you should just be able to do <up> or something similar in `terminal` mode. For `<C-p>` and `<C-n>` you can create mappings in terminal mode.

For saving the output of the terminal with the session itself is more complicated.

**Comment by nyngwang** [comment]
> The last command or the output of the last command? [...]

The last command, not the output. Nevermind I will record a demo for this after another issue is resolved.

**Comment by GnikDroy** [comment]
I did some research, and it turns out saving the output of the terminal might be possible. But, it might not be a very easy task.

You have to do the following:

1) When opening any new terminal, the underlying function `termopen()` must be passed with `on_stdout` and `on_stderr` callbacks. This ensures ANSI escape sequences are captured. In the callbacks, we store the output of stdout and stderr in `projections_terminal_history/....`, it is probably also necessary to store `width` and `height` of the pty.

2) When restoring terminals, we have to get the channel_id and pass `projections_terminal_history/..` data into the channel. This respects ANSI escape sequences. See `nvim_open_term`.

The problem is, we have no way to force the user to open new terminal buffers with our configured `on_stdout` and `on_stderr` callbacks. There might be problems along the way, or a much simpler solution. Only way to know is start to implementing this.

I will keep this feature in mind, which is indeed useful. I will keep this issue open for any interested contributors.
