### ISSUE TITLE
[Enh./Bug] I think this should be done to the current switcher implementation.

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#15]
Let me give you a scenario explaining what's the problem and what should be provided IMOO:

1. Say I'm currently at path `~/.config/nvim`, which is a project directory. Then within this project directory, I have an unsaved file(let's call it `A`).
2. Next, assume the project is pretty big, so I forgot that I have `A` unsaved at some point.
3. Unfortunately, I changed `cwd` in some way without saving `A` first.
4. Now I did see your careful message:
    ```
    projections: Unsaved buffers. Unable to switch projects
    ```
5. So what? (Not to be rude but just to mimic the sound from a real user's heart) **I have already changed** `cwd`(Let's assume that the change of `cwd` is done in the background, so it's hard for the user to go back)! If you did know that I have some unsaved file(s) when `cwd` was still pointing to a project, you should provide a way for me to get this info too, so I can stop my action there before I called any commend that changed `cwd`.

In my case(as you have seen in my previous issues), I use neo-tree to change my `cwd`. If I can know whether there are some unsaved files under the current project, I will be able to add a sentinel to neo-tree to make the keymap do its work more carefully.

Maybe you have a better idea of how to solve this problem. Feel free to point out anything wrong. Thanks for your reading.

**Comment by GnikDroy** [comment]
So, suppose you want to check in `neo-tree` if you can `cd` into a project directory.

You firstly check `Session.info(target_dir)`. This will result in `nil` if the target directory is not a project directory. If the target directory is not a project directory, you can safely `cd` into that directory. (Switching cannot happen if the target is not a project)

Now, if the target directory is a project directory. i.e `Session.info` returns a non-nil value, then you check if any buffers are unsaved. The small for-loop in `utils` does this (shown below). If unsaved buffers are present, you abort the `cd`.

https://github.com/GnikDroy/projections.nvim/blob/be100ad3540952542c2a1135f39cddea8a1a00de/lua/projections/utils.lua#L3-L10

The reason `_unsaved_buffers_present` is not exposed is that this is a very simple function < 10 LOC, and is not specific to projections. This is how you check if you have unsaved buffers everywhere.

**Comment by GnikDroy** [comment]
I don't think I need to change anything in projections though, because projections doesn't use `DirChangedPre`.

If you want something to change in projections, can you perhaps provide a sample implementation, or perhaps which line should be added/changed/removed?

**Comment by nyngwang** [comment]
@GnikDroy: Sorry for my late reply, fell asleep.

My motivation was to achieve the effect built-in to vim/neovim: when one tries to run `:qa` when any buffer unsaved it will show a red line in the command line and jump to an unsaved buffer. This provides a very good UX so I thought projections.nvim should have it if can have it.

> I don't think I need to change anything in projections though, because projections doesn't use `DirChangedPre`.

I think you're right, sorry for my bad issue. I think my current problem is that I don't quite understand the difference between `switcher.switch` and `session.restore`. So it seems like the latter one is just an extension of the former one?

**Comment by GnikDroy** [comment]
> I think my current problem is that I don't quite understand the difference between switcher.switch and session.restore. So it seems like the latter one is just an extension of the former one? 

Okay so let me explain, both of these are useful functions, but have different uses.

## Session.restore()

`Session.restore` indiscriminately restores the session of project X. It doesn't care about, unsaved buffers, having to save the current project session, clearing buffers and jumplist etc. If you look at the source you will see that `Session.restore()` is the bare `:source <session_file>` command with hooks. `Session.restore` is preferred when vim has just started, because then there are no unsaved buffers, empty jumplist etc... Use this to ONLY restore a session.

## switcher.switch()
`switcher.switch()` is a bit more careful. It checks if there are unsaved buffers, saves the current project session, clears the buffer list / jump list. If everything went fine, it then only restores the session (calls Session.restore()). Use this when you want to "switch" between sessions / projects. This is the preferred mechanism to switch between projects, because it doesn't assume the current vim session is "clean".

Usually, using `switcher.switch()` instead of `Session.restore()` has no disadvantage. Because `switcher.switch()` just performs additional checks which are generally useful. But in certain situations, `Session.restore()` is also useful (when you only want `:source` with hooks).

**Comment by GnikDroy** [comment]
The problem with `DirChangedPre` is projections has no control of whether to stop changing directory.

`DirChangedPre` event means "Hey, I'm going to change directory now, just letting you know".
Projections will abort session restore when unsaved buffers are present, and give you the error message.

But a 'DirChangedPre` means there is going to be `DirChanged`, projections can't stop this.

**Comment by GnikDroy** [comment]
Also, if you want to change `neo-tree's` `cd` behaviour. You can do the following.

```lua
local Session = require("projections.session")
local switcher = require("projections.switcher")

function cd_that_changes_projects(target_dir)
   local is_project_dir = Session.info(target_dir) ~= nil
   if is_project_dir then
       switcher.switch(target_dir)
   else
       vim.cmd.cd(target_dir)
   end
end
```

**Comment by nyngwang** [comment]
To @GnikDroy:

> `switcher.switch()` is a bit more careful. It checks if there are unsaved buffers, saves the current project session, clears the buffer list / jump list.

So does it help me save those unsaved buffers? (Still reading and will update this comment at any time)

**Comment by nyngwang** [comment]
> If you look at the source you will see that `Session.restore()` is the bare `:source <session_file>` command with hooks.

I think now my question becomes: does the default `:source` help me save those unsaved buffers? Or all the changes will be discarded.

**Comment by GnikDroy** [comment]
The default `:source` never deletes buffers, so this never comes into consideration.

If you have buffer X, Y open and `:source another_session.vim` then the buffers X, Y will still be present after the source command. `switcher.switch()` is responsible for deleting existing buffers, because people don't want buffers from previous projects open when switching to a new one.

**Comment by nyngwang** [comment]
@GnikDroy So if there are unsaved buffers, would `switcher.switch()` change `cwd` even if it will send the warning via `vim.notify`?
